<!--
Magento Twitter Extension - emalltwitter
Copyright (C) 2012  SMDesign - www.smdesign.rs/www.extensionsmall.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

If you like our Extensions please keep the link at the bottom of widget.

-->

<?php
$twitterConfig = $this->getTwitterConfig();
$twitterConfigEnabled = ($twitterConfig['enabled']!='') ? $twitterConfig['enabled'] : '1';
$twitterConfigTwitterFeed = ($twitterConfig['twitter_feed']!='') ? $twitterConfig['twitter_feed'] : 'extensionsmall';
$twitterConfigTwitterApi= ($twitterConfig['twitter_api']!='') ? $twitterConfig['twitter_api'] : '349071818910494720';
$twitterConfigTwitterFeedNumber = ($twitterConfig['twitter_feed_number']!='') ? $twitterConfig['twitter_feed_number'] : '0';
$twitterConfigTwitterBoxSide = ($twitterConfig['twitter_box_side']!='') ? $twitterConfig['twitter_box_side'] : '1';
$twitterConfigTwitterBoxTopPosition = $twitterConfig['twitter_box_top_position']!='' ? $twitterConfig['twitter_box_top_position'] : '50px';
$twitterConfigTwitterBoxWidth = ($twitterConfig['twitter_box_width']!='') ? $twitterConfig['twitter_box_width'] : '300';
$twitterConfigTwitterBoxHeight = ($twitterConfig['twitter_box_height']!='') ? $twitterConfig['twitter_box_height'] : '300';
$twitterConfigTwitterBoxBackground = ($twitterConfig['twitter_box_background']!='') ? $twitterConfig['twitter_box_background'] : '#333333';
$twitterConfigTwitterTweetsLinkColor = ($twitterConfig['twitter_tweets_link_color']!='') ? $twitterConfig['twitter_tweets_link_color'] : '#4aed05';
$twitterConfigTwitterChromeValues = ($twitterConfig['twitter_chrome_values']!='') ? $twitterConfig['twitter_chrome_values'] : 'transparent';
$twitterConfigTwitterTheme = ($twitterConfig['twitter_theme']!='') ? $twitterConfig['twitter_theme'] : 'dark';
?>
<?php if($twitterConfigEnabled == 1): ?>
	<style type="text/css">
		div.emalltwitter-wraper{
			z-index: 1000;
			position:fixed;
			top:<?php echo $twitterConfigTwitterBoxTopPosition ?>px;
            width: <?php echo $twitterConfigTwitterBoxWidth ?>px;
		}
		div.emalltwitter-wraper.left{
			left:0px;
		}
		div.emalltwitter-wraper.right{
			right:0px;
		}
		div#emalltwitter{
			float:left;
			background: <?php echo $twitterConfigTwitterBoxBackground ?>;
			opacity: 0.85;
		}
		div#emalltwitter label {
			color: <?php echo $twitterConfigTwitterTweetsColor ?>; 
			background: <?php echo $twitterConfigTwitterBoxBackground ?>;
			border-radius: 0 0 9px 9px !important;
			color: #FFFFFF;
			float: left;
			opacity: 0.85;
			padding: 5px;
			width: 96%;
		}
		.twtr-doc {
			border-radius: 5px 5px 0px 0px !important;
		}
		div#emalltwitter label a{
			text-decoration:none;
			color:<?php echo $twitterConfigTwitterTweetsLinkColor ?>;
		}
		div#emalltwitter label a:hover{
			text-decoration:underline;
		}
		div.emalltwitter-wraper.left div#emalltwitter{
			border-radius: 5px 5px 10px 10px;
			box-shadow: 3px 3px 10px <?php echo $twitterConfigTwitterBoxBackground ?>;
			padding: 0 5px;
		}
		div.emalltwitter-wraper.right div#emalltwitter{
			border-radius: 10px 0 10px 10px;
			box-shadow: 0 4px 18px <?php echo $twitterConfigTwitterBoxBackground ?>;
			padding: 0 5px;
		}
		#emalltwitter-open{
			background: #3e3e3e;
			background: <?php echo $twitterConfigTwitterBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emalltwitter/twitter-button.png") ?>) no-repeat 6px 6px <?php echo $twitterConfigTwitterBoxBackground ?>;
			color:<?php echo $twitterConfigTwitterTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			transition: all 0.1s ease 0.2s;
			height: 30px;
			width: 30px;
			padding: 6px;
		}
		.emalltwitter-wraper.right #emalltwitter-open.open {
			background: #3e3e3e;
			background: <?php echo $twitterConfigTwitterBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emalltwitter/twitter-button-hover.png") ?>) no-repeat 6px 6px <?php echo $twitterConfigTwitterBoxBackground ?>;
			color:<?php echo $twitterConfigTwitterTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			height: 30px;
			width: 90px;
			padding: 6px;
		}
		.emalltwitter-wraper.left #emalltwitter-open.open {
			background: #3e3e3e;
			background: <?php echo $twitterConfigTwitterBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emalltwitter/twitter-button-hover.png") ?>) no-repeat 6px 6px <?php echo $twitterConfigTwitterBoxBackground ?> ;
			color:<?php echo $twitterConfigTwitterTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			height: 30px;
			width: 90px;
			padding: 6px;
		}
		#emalltwitter-open:hover { transition: all .2s; background: url( <?php  echo $this->getSkinUrl("images/emalltwitter/twitter-button-hover.png") ?>) no-repeat 6px 6px <?php echo $twitterConfigTwitterBoxBackground ?>; padding-left: 70px; }
		.emalltwitter-wraper.left #emalltwitter-open{
			border-radius: 0 27px 27px 0;
			margin-bottom: 1px;
		}
		.emalltwitter-wraper.right #emalltwitter-open{
			border-radius: 25px 0 0 27px;
			float: right;
			margin-bottom: 1px;
		}        
        #twitter-widget-0 {
            height: <?php echo $twitterConfigTwitterBoxHeight; ?>px !important;
            
        }

  
		
	</style>
	<script type="text/javascript">
		function createCookie(name,value,days) {
			if (days) {
				var date = new Date();
				date.setTime(date.getTime()+(days*24*60*60*1000));
				var expires = "; expires="+date.toGMTString();
			}
			else var expires = "";
			document.cookie = name+"="+value+expires+"; path=/";
		}
		function readCookie(name) {
			var nameEQ = name + "=";
			var ca = document.cookie.split(';');
			for(var i=0;i < ca.length;i++) {
				var c = ca[i];
				while (c.charAt(0)==' ') c = c.substring(1,c.length);
				if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
			}
			return null;
		}
		function eraseCookie(name) {
			createCookie(name,"",-1);
		}
		function setState(){
			if(readCookie('emalltwitt')==null){
				createCookie('emalltwitt','hide',1);
				$('emalltwitter-open').className="";
				$('emalltwitter-open').addClassName('close');
			} else {
				eraseCookie('emalltwitt');
				$('emalltwitter-open').className="";
				$('emalltwitter-open').addClassName('open');
			}
		}
		function checkCookie() {
			if(readCookie('emalltwitt')=='hide'){
				$('emalltwitter').hide();
			} else {
				$('emalltwitter-open').className="";
				$('emalltwitter-open').addClassName('open');
			}
		}
	</script>

	<div class="emalltwitter-wraper <?php if($twitterConfigTwitterBoxSide==1){ echo('left'); } else { echo('right'); } ;?>" id="emalltwitter-wraper">
		<a id="emalltwitter-open" onclick="$('emalltwitter').toggle('blind');  setState(); return false;" href="#">&nbsp;</a>
		<br />
		<div class="emalltwitter" id="emalltwitter">
			<div id="toggle">
				<a class="twitter-timeline" 
        href="https://twitter.com/<?php echo $twitterConfigTwitterFeed ?>" 
        data-chrome="<?php echo str_replace(',',' ', $twitterConfigTwitterChromeValues); ?>"
        width="<?php echo $twitterConfigTwitterBoxWidth; ?> px" 
        data-link-color="<?php echo $twitterConfigTwitterTweetsLinkColor; ?>"
        data-theme="<?php echo $twitterConfigTwitterTheme; ?>"
        height="<?php echo $twitterConfigTwitterBoxHeight; ?> px"                   
        data-widget-id="<?php echo $twitterConfigTwitterApi; ?>"
        data-tweet-limit="<?php echo $twitterConfigTwitterFeedNumber; ?>">
        
        Tweets by @<?php echo $twitterConfigTwitterFeed ?></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

				<label>Provided by <a href="http://www.extensionsmall.com/" target="_blank"><span style="float: right; padding-right: 15px;">Extensions Mall</span></a></label>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		checkCookie();
	</script>
<?php endif; ?>

