<?php
/*
  Magento Twitter Extension - emalltwitter
  Copyright (C) 2012  SMDesign - www.smdesign.rs/www.extensionsmall.com

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  If you like our Extensions please keep the link at the bottom of widget.
 */

if ($this->isEnabled()):
    ?>
    <div class="emalltwitter-wraper <?php echo $this->getBoxSide() ?>" id="emalltwitter-wraper" style="top:<?php echo $this->getBoxTopPosition() ?>px;width:<?php echo $this->getBoxWidth() ?>px;">
        <a id="emalltwitter-open" href="#" style="background-color:<?php echo $this->getBoxBackground() ?>">&nbsp;</a>
        <br />
        <div class="emalltwitter" id="emalltwitter" style="background-color:<?php echo $this->getBoxBackground() ?>; display:none;">
            <div id="toggle">
                <a class="twitter-timeline"
                   href="https://twitter.com/<?php echo $this->getFeed() ?>"
                   data-widget-id="<?php echo $this->getWidgetId() ?>"
                   width="<?php echo $this->getWidth() ?>"
                   height="<?php echo $this->getHeight() ?>"
                   data-tweet-limit="<?php echo $this->getTweetLimit() ?>"
                   data-theme="<?php echo $this->getTheme() ?>"
                   data-link-color="<?php echo $this->getLinkColor() ?>"
                   data-chrome="<?php echo $this->getChrome() ?>"
                   >Tweets by <?php echo $this->getFeed() ?></a>
                <script>!function (d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
                        if (!d.getElementById(id)) {
                            js = d.createElement(s);
                            js.id = id;
                            js.src = p + "://platform.twitter.com/widgets.js";
                            fjs.parentNode.insertBefore(js, fjs);
                        }
                    }(document, "script", "twitter-wjs");</script>
                <label>Provided by <a href="http://www.extensionmall.com/" target="_blank">Extensions Mall</a></label>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            if (null !== Mage.Cookies.get('emalltwitt') && Mage.Cookies.get('emalltwitt') === 'show') {
                $('emalltwitter-open').addClassName('open');
                $('emalltwitter').show();
            }
        });
        $('emalltwitter-open').observe('click', function (event) {
            event.preventDefault();
            if (null !== Mage.Cookies.get('emalltwitt') && Mage.Cookies.get('emalltwitt') === 'show') {
                Mage.Cookies.set('emalltwitt', 'hide');
                $('emalltwitter-open').removeClassName('open');
                $('emalltwitter').hide();
            } else {
                Mage.Cookies.set('emalltwitt', 'show');
                $('emalltwitter-open').addClassName('open');
                $('emalltwitter').show();
            }
        });
    </script>
    <?php
 endif;